apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP  # Keeps it internal within the cluster
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
