
# FROM node:18-alpine


# WORKDIR /app


# COPY package*.json ./


# RUN npm install


# COPY . .


# EXPOSE 8000


# CMD ["npm", "start"]


# First stage: Build environment
FROM node:18-alpine AS builder
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy the rest of the application code
COPY . .

# Second stage: Production environment
FROM node:18-alpine
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app /app

# Expose the backend port
EXPOSE 8000

# Start the backend using npm
CMD ["npm", "start"]

