apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30007  # Optional: specify a port between 30000-32767 for NodePort
